### ISSUE TITLE
cannot find gz file

### ISSUE THREAD

**Issue by tigerneil** [pmargreff/juliavm#3]
neil@neil-workstation:~/Downloads/juliavm$ juliavm install 1.0.0-rc1
https://julialang.s3.amazonaws.com/bin/linux/x64/1.0/julia-1.0.0-rc1-linux-x86_64.tar.gz isn't available
You can list all available versions with ls-remote
neil@neil-workstation:~/Downloads/juliavm$ juliavm install 0.7.0-rc3
https://julialang.s3.amazonaws.com/bin/linux/x64/0.7/julia-0.7.0-rc3-linux-x86_64.tar.gz isn't available
You can list all available versions with ls-remote
neil@neil-workstation:~/Downloads/juliavm$

**Comment by pmargreff** [comment]
Hello @tigerneil 

thank you for the report, I'll take a look ASAP, can you provide me your OS and kernel versions?

**Comment by tigerneil** [comment]
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.5 LTS
Release:	16.04
Codename:	xenial

Linux version 4.13.0-39-generic (buildd@lcy01-amd64-024) (gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.9)) #44~16.04.1-Ubuntu SMP Thu Apr 5 16:43:10 UTC 2018

**Comment by jeffhx** [comment]
i can confirm the issue happens on my machine:
```bash
hong@hong-UX305CA:~$ juliavm ls-remote | grep 1.0
1.0.0
1.0.0-rc1
hong@hong-UX305CA:~$ juliavm install 1.0.0
https://julialang.s3.amazonaws.com/bin/linux/x64/1.0/julia-1.0.0-linux-x86_64.tar.gz isn't available
You can list all available versions with ls-remote
```

```
hong@hong-UX305CA:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.1 LTS
Release:	18.04
Codename:	bionic
```

**Comment by jeffhx** [comment]
it looks that the binary files on https://julialang.s3.amazonaws.com/ is not in sync with the released versions on github. I wonder if there is an automatic process here, and if the process is broken.

**Comment by jeffhx** [comment]
@pmargreff pull request submitted:
https://github.com/pmargreff/juliavm/pulls

**Comment by tigerneil** [comment]
solved.
