### ISSUE TITLE
Running scripts under zsh leaves user in bash

### ISSUE THREAD

**Issue by sarna** [pmargreff/juliavm#6]
As in title. I'd expect them not to change my shell to bash :)

**Comment by pmargreff** [comment]
> As in title. I'd expect them not to change my shell to bash :)

Does PR #7 fix this issue?

**Comment by pmargreff** [comment]
> As in title. I'd expect them not to change my shell to bash :)

@sarna PR #7 does fix this issue?

**Comment by sarna** [comment]
Yup, it's fixed now :)
